language: node_js
node_js:
  - '11'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - echo 'Build starts!!!'
  - npm run build
  #- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox