language: node_js
node_js:
  - '11'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli

  script:
    ng build
#  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox